<html>
<head>
 <title>Temporal.PW - Temporary secure storage for passwords</title>
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>

<style type="text/css">
  body { background: #d3d3d3 !important; }
</style>

<div class="container">

<h1>About <a href="/">Temporal.PW</a> :</h1><br/>
<h3>
<a href="/">Temporal.PW</a> can convert a password into a secure temporary URL that is safe to send via E-Mail.<br/>
<br/>
I made this because I needed a simple way to send passwords to people with whom I didn't already have end-to-end encryption established.<br/>
</h3>
<br/>

<h4>
<ul>
  <li>All encryption / decryption is done in the browser, so the server only ever sees an encrypted copy of the password.</li><br/>
  <li>The encrypted passwords are deleted after their expiration date or after being viewed a single time.</li><br/>
  <li>The (128 bit AES-CTR) password encryption key is generated by the browser and is never sent to the server.</li><br/>
  <li>The browser encrypts the password, sends only the encrypted version of the password to the server, and generates a temporary URL that holds the actual decryption key.</li><br/>
  <li>The decryption key is stored in the 'fragment' part of the URL (after the "#" hash symbol) that is never sent to the server.</li><br/>
  <li>The server permanently deletes the encrypted password after the expiration date or after it is viewed a <b>single</b> time.</li><br/>
  <li>You can choose to tell the server to only allow a password to be viewed from your same IP address (useful for sending passwords to someone in the same office / network).</li><br/>
<br/>
  <li>If the E-Mail recipient <b>is</b> able to view the password: you know that nobody else saw it because each temporary URL can only be viewed a <b>single</b> time.</li><br/>
  <li>If the E-Mail recipient is <b>unable</b> to view the password: it may have been intercepted and viewed by someone else, so you know that you need to create a <b>new</b> password for them and send them a new <a href="/">Temporal.PW</a> password URL for it.</li><br/>
  <li>If the E-Mail is ever read sometime in the future by someone malicious on either end: the <a href="/">Temporal.PW</a> password URL cannot be used to determine what the password is / was.  (because it only contains the decryption key, and the server has already deleted the corresponding encrypted version of the password)</li><br/>
<br/>
  <li>Easy to audit: only ~150 lines of python for the backend, and ~200 lines of JavaScript for the fronend.</li><br/>
  <li><a href="http://github.com/tkooda/temporalpw">100% open source</a>.</li><br/>
  <li>Uses common <a href="http://bottlepy.org/">Bottle</a> framework for the backend; <a href="https://jquery.com/">jQuery</a>, <a href="http://getbootstrap.com/">bootstrap</a>, and <a href="http://zeroclipboard.org/">ZeroClipboard</a> for the frontend; and <a href="https://github.com/ricmoo/aes-js">AES-JS</a>, <a href="https://github.com/45678/Base58">Base58</a>, and <a href="https://github.com/jprichardson/secure-random">secure-random</a> for the in-browser cryptography.</li><br/>
  <li>If you'd like to help keep this service free forever: you can send a few pennies via Bitcoin to: <a href="bitcoin:1MLaaKmMbioyCKZShbyKGJztUP8M7BHRYp">1MLaaKmMbioyCKZShbyKGJztUP8M7BHRYp</a></li><br/>
</ul>

</h4>
<br/>
<center>
<a href="/">Send another password</a> | <a href="https://github.com/tkooda/temporalpw">Source</a></br>
</center>

<br/>
<br/>

</div>

</body>
</html>
